// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// USER CHECK ROLE
export const CHECK_ROLE_REQUEST = 'CHECK_ROLE_REQUEST';
export const CHECK_ROLE_SUCCESS = 'CHECK_ROLE_SUCCESS';
export const CHECK_ROLE_FAILURE = 'CHECK_ROLE_FAILURE';

// PROFILE WORKERS
export const FETCH_WORKER_REQUEST = 'FETCH_WORKER_REQUEST';
export const FETCH_WORKER_SUCCESS = 'FETCH_WORKER_SUCCESS';
export const FETCH_WORKER_FAILURE = 'FETCH_WORKER_FAILURE';

// UPDATE PROFILE WORKER
export const UPDATE_WORKER_SUCCESS = 'UPDATE_WORKER_SUCCESS';
export const UPDATE_WORKER_PHOTO_SUCCESS = 'UPDATE_WORKER_PHOTO_SUCCESS';


// PROFILE RECRUITERS
export const FETCH_RECRUITER_REQUEST = 'FETCH_RECRUITER_REQUEST';
export const FETCH_RECRUITER_SUCCESS = 'FETCH_RECRUITER_SUCCESS';
export const FETCH_RECRUITER_FAILURE = 'FETCH_RECRUITER_FAILURE';

// UPDATE PROFILE RECRUITERS
export const UPDATE_RECRUITER_SUCCESS = 'UPDATE_RECRUITER_SUCCESS';
export const UPDATE_RECRUITER_PHOTO_SUCCESS = 'UPDATE_RECRUITER_PHOTO_SUCCESS';

// PORTFOLIO WORKERS
export const FETCH_PORTFOLIO_REQUEST = 'FETCH_PORTFOLIO_REQUEST';
export const FETCH_PORTFOLIO_SUCCESS = 'FETCH_PORTFOLIO_SUCCESS';
export const FETCH_PORTFOLIO_FAILURE = 'FETCH_PORTFOLIO_FAILURE';

// EXPERIENCE WORKERS
export const FETCH_EXPERIENCE_REQUEST = 'FETCH_EXPERIENCE_REQUEST';
export const FETCH_EXPERIENCE_SUCCESS = 'FETCH_EXPERIENCE_SUCCESS';
export const FETCH_EXPERIENCE_FAILURE = 'FETCH_EXPERIENCE_FAILURE';

// SKILL WORKERS
export const FETCH_SKILL_REQUEST = 'FETCH_SKILL_REQUEST';
export const FETCH_SKILL_SUCCESS = 'FETCH_SKILL_SUCCESS';
export const FETCH_SKILL_FAILURE = 'FETCH_SKILL_FAILURE';

// ADD HIRE
export const ADD_HIRE_REQUEST = 'ADD_HIRE_REQUEST';
export const ADD_HIRE_SUCCESS = 'ADD_HIRE_SUCCESS';
export const ADD_HIRE_FAILURE = 'ADD_HIRE_FAILURE';